---
- name: Deploy Billing API
  hosts: ec2
  become: true

  vars:
    app_dir: /opt/billing

  tasks:
    - name: Create app directory
      file:
        path: "{{ app_dir }}"
        state: directory

    - name: Copy compose file
      copy:
        src: docker-compose.prod.yml
        dest: "{{ app_dir }}/docker-compose.yml"

    - name: Copy nginx config
      copy:
        src: nginx.conf
        dest: "{{ app_dir }}/nginx.conf"
        mode: "0644"

    - name: Copy env file
      copy:
        src: .env
        dest: "{{ app_dir }}/.env"

    - name: Start containers
      shell: |
        cd {{ app_dir }}
        docker compose up -d
